### ISSUE TITLE
Error editing commands.json entry with allowParams missing

### ISSUE THREAD

**Issue by rvmey** [GussSoares/triggercmd-cli#3]
# triggercmd edit
...
? Select a command: python test
? Type the command name: python test
? Type the command: python /root/test.py
? Select a command ground: background
? Type the command voice: python
**Error: 'allowParams'**

This is my commands.json entry.  Notice it doesn't have an **allowParams** value.  
{"trigger":"python test","command":"python /root/test.py","ground":"background","voice":""},

The agent is ok with a missing allowParams value.

**Comment by GussSoares** [comment]
Hi @rvmey, thanks for your comment. This is a really problem. I will fix this and release again.
